"""Added tokens table

Revision ID: 1599705b2dfe
Revises: 9fc66c70fbe8
Create Date: 2022-10-19 22:16:40.449605

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1599705b2dfe"
down_revision = "9fc66c70fbe8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("token", sa.VARCHAR(length=64), nullable=False),
        sa.Column("team_description", sa.VARCHAR(length=128), nullable=False),
        sa.PrimaryKeyConstraint("token"),
        sa.UniqueConstraint("team_description"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens")
    # ### end Alembic commands ###
