"""Added models table

Revision ID: 19ccc11cccc6
Revises: 637cf903d37b
Create Date: 2022-10-12 09:58:21.169289

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "19ccc11cccc6"
down_revision = "637cf903d37b"
branch_labels = None
depends_on = None

SERVER_UUID = sa.text("gen_random_uuid()")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("model_id", postgresql.UUID(), nullable=False, server_default=SERVER_UUID),
        sa.Column("team_id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), nullable=False),
        sa.Column("description", sa.VARCHAR(length=256), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.team_id"],
        ),
        sa.PrimaryKeyConstraint("model_id"),
    )
    op.create_index("team_model_idx", "models", ["team_id", "name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("team_model_idx", table_name="models")
    op.drop_table("models")
    # ### end Alembic commands ###
