"""Added metrics table

Revision ID: 9fc66c70fbe8
Revises: 01d29d9e5f5a
Create Date: 2022-10-13 13:55:07.870680

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9fc66c70fbe8"
down_revision = "01d29d9e5f5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metrics",
        sa.Column("trial_id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), nullable=False),
        sa.Column("value", sa.FLOAT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trial_id"],
            ["trials.trial_id"],
        ),
        sa.PrimaryKeyConstraint("trial_id", "name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metrics")
    # ### end Alembic commands ###
