"""Added teams table

Revision ID: 637cf903d37b
Revises: 3d5ad862d83d
Create Date: 2022-10-11 14:12:02.644936

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "637cf903d37b"
down_revision = "3d5ad862d83d"
branch_labels = None
depends_on = None

SERVER_UUID = sa.text("gen_random_uuid()")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("team_id", postgresql.UUID(), nullable=False, server_default=SERVER_UUID),
        sa.Column("title", sa.VARCHAR(length=128), nullable=False),
        sa.Column("chat_id", sa.BIGINT(), nullable=False),
        sa.Column("api_base_url", sa.VARCHAR(length=256), nullable=False),
        sa.Column("api_key", sa.VARCHAR(length=128), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("team_id"),
        sa.UniqueConstraint("api_base_url"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_teams_chat_id"), "teams", ["chat_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teams_chat_id"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
