"""remove_team_titles

Revision ID: b6cd81907a19
Revises: 1599705b2dfe
Create Date: 2023-10-17 22:43:19.213387

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6cd81907a19"
down_revision = "1599705b2dfe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("teams_title_key", "teams", type_="unique")
    op.drop_column("teams", "title")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("title", sa.VARCHAR(length=128)))
    op.create_unique_constraint("teams_title_key", "teams", ["title"])
    # ### end Alembic commands ###
